ErrorDocument 404 /drupal/page-not-found
ErrorDocument 403 /drupal/forbidden
ErrorDocument 500 /drupal/server-error
ErrorDocument 503 /drupal/server-unavailable
ErrorDocument 401 /drupal/unauthorized
ErrorDocument 400 /drupal/bad-request
ErrorDocument 405 /drupal/method-not-allowed
ErrorDocument 408 /drupal/request-timeout
