# This configuration requires mod_ssl, mod_socache_shmcb, mnod_rewrite, and mod_headers
<VirtiaulHost *:80>
    RequestHeader unset X-Forwarded-Proto
    RewriteEngine On
    RewriteRule ^ https://%{HTTP_HOST}$1 [R=301,L]
</VirtualHost>
<VirtualHost *:443>
    RequestHeader unset X-Forwarded-Proto
    ServerName localhost
    ServerAdmin {{ admin_email }}
    DocumentRoot /var/www/html/drupal
    SSLCertificateFile /etc/httpd/ssl/ssl.cert
    SSLCertificateKeyFile /etc/httpd/ssl/ssl.key
    <Directory {{ drupal_root }}>
        Options FollowSymLinks
        AllowOverride All
        Require all granted
    </Directory>

    ErrorLog ${APACHE_LOG_DIR}/error.log
    CustomLog ${APACHE_LOG_DIR}/access.log combined

    SSLEngine on
    SSLCertificateFile /etc/ssl/certs/{{ ssl_cert_file }}
    SSLCertificateKeyFile /etc/ssl/private/{{ ssl_key_file }}
